### ISSUE TITLE
Test failures when running python unit  tests

### ISSUE THREAD

**Issue by brat000012001** [brat000012001/riffcash-core#1]
There are test failures when running python unit tests:

To reproduce,
test/functional/test_runner.py

```
...............
uptime.py passed, Duration: 8 s
....................
listsinceblock.py passed, Duration: 42 s
.
resendwallettransactions.py passed, Duration: 11 s
.................................................................
wallet-hd.py passed, Duration: 597 s
.............
import-rescan.py passed, Duration: 92 s

TEST                           | STATUS    | DURATION

abandonconflict.py             | ✓ Passed  | 36 s
bip65-cltv-p2p.py              | ✖ Failed  | 0 s
bip68-112-113-p2p.py           | ✖ Failed  | 0 s
bipdersig-p2p.py               | ✖ Failed  | 0 s
blockchain.py                  | ✓ Passed  | 14 s
bumpfee.py                     | ✖ Failed  | 0 s
decodescript.py                | ✖ Failed  | 0 s
disablewallet.py               | ✓ Passed  | 4 s
disconnect_ban.py              | ✖ Failed  | 0 s
fundrawtransaction.py          | ✓ Passed  | 172 s
getchaintips.py                | ✓ Passed  | 27 s
httpbasics.py                  | ✓ Passed  | 17 s
import-rescan.py               | ✓ Passed  | 92 s
importmulti.py                 | ✓ Passed  | 56 s
importprunedfunds.py           | ✓ Passed  | 21 s
invalidblockrequest.py         | ✖ Failed  | 0 s
invalidtxrequest.py            | ✖ Failed  | 0 s
keypool-topup.py               | ✓ Passed  | 97 s
keypool.py                     | ✓ Passed  | 21 s
listsinceblock.py              | ✓ Passed  | 42 s
listtransactions.py            | ✖ Failed  | 0 s
mempool_limit.py               | ✓ Passed  | 24 s
mempool_persist.py             | ✖ Failed  | 0 s
mempool_reorg.py               | ✓ Passed  | 15 s
mempool_resurrect_test.py      | ✓ Passed  | 8 s
mempool_spendcoinbase.py       | ✓ Passed  | 5 s
merkle_blocks.py               | ✓ Passed  | 36 s
mining.py                      | ✖ Failed  | 0 s
multi_rpc.py                   | ✓ Passed  | 12 s
multiwallet.py                 | ✓ Passed  | 27 s
net.py                         | ✓ Passed  | 14 s
nulldummy.py                   | ✖ Failed  | 0 s
p2p-compactblocks.py           | ✖ Failed  | 0 s
p2p-fullblocktest.py           | ✖ Failed  | 0 s
p2p-leaktests.py               | ✖ Failed  | 0 s
p2p-mempool.py                 | ✖ Failed  | 0 s
p2p-segwit.py                  | ✖ Failed  | 0 s
p2p-versionbits-warning.py     | ✖ Failed  | 0 s
preciousblock.py               | ✓ Passed  | 25 s
prioritise_transaction.py      | ✖ Failed  | 0 s
proxy_test.py                  | ✓ Passed  | 23 s
rawtransactions.py             | ✓ Passed  | 54 s
receivedby.py                  | ✓ Passed  | 44 s
reindex.py                     | ✓ Passed  | 27 s
resendwallettransactions.py    | ✓ Passed  | 11 s
rest.py                        | ✓ Passed  | 35 s
rpcnamedargs.py                | ✓ Passed  | 7 s
segwit.py                      | ✖ Failed  | 0 s
sendheaders.py                 | ✖ Failed  | 0 s
signmessages.py                | ✓ Passed  | 8 s
signrawtransactions.py         | ✓ Passed  | 8 s
test_script_address2.py        | ✓ Passed  | 27 s
txn_clone.py                   | ✓ Passed  | 34 s
txn_doublespend.py --mineblock | ✓ Passed  | 36 s
uptime.py                      | ✓ Passed  | 8 s
wallet-accounts.py             | ✓ Passed  | 74 s
wallet-dump.py                 | ✓ Passed  | 30 s
wallet-encryption.py           | ✓ Passed  | 20 s
wallet-hd.py                   | ✓ Passed  | 597 s
wallet.py                      | ✓ Passed  | 179 s
walletbackup.py                | ✖ Failed  | 269 s
zapwallettxes.py               | ✓ Passed  | 34 s
zmq_test.py                    | ✓ Passed  | 15 s

ALL                            | ✖ Failed  | 2305 s (accumulated) 
```

**Comment by brat000012001** [comment]
After having fixed a typo in test/functional/test_framework/mininode.py, the tests are *mostly* running with exception of two tests that are still failing:

```
TEST                           | STATUS    | DURATION

abandonconflict.py             | ✓ Passed  | 24 s
bip65-cltv-p2p.py              | ✓ Passed  | 31 s
bip68-112-113-p2p.py           | ✓ Passed  | 29 s
bipdersig-p2p.py               | ✓ Passed  | 15 s
blockchain.py                  | ✓ Passed  | 11 s
bumpfee.py                     | ✓ Passed  | 36 s
decodescript.py                | ✓ Passed  | 4 s
disablewallet.py               | ✓ Passed  | 4 s
disconnect_ban.py              | ✓ Passed  | 12 s
fundrawtransaction.py          | ✓ Passed  | 149 s
getchaintips.py                | ✓ Passed  | 21 s
httpbasics.py                  | ✓ Passed  | 13 s
import-rescan.py               | ✓ Passed  | 67 s
importmulti.py                 | ✓ Passed  | 37 s
importprunedfunds.py           | ✓ Passed  | 16 s
invalidblockrequest.py         | ✓ Passed  | 8 s
invalidtxrequest.py            | ✓ Passed  | 7 s
keypool-topup.py               | ✓ Passed  | 59 s
keypool.py                     | ✓ Passed  | 15 s
listsinceblock.py              | ✓ Passed  | 31 s
listtransactions.py            | ✓ Passed  | 58 s
mempool_limit.py               | ✓ Passed  | 31 s
mempool_persist.py             | ✓ Passed  | 35 s
mempool_reorg.py               | ✓ Passed  | 11 s
mempool_resurrect_test.py      | ✓ Passed  | 5 s
mempool_spendcoinbase.py       | ✓ Passed  | 6 s
merkle_blocks.py               | ✓ Passed  | 26 s
mining.py                      | ✓ Passed  | 10 s
multi_rpc.py                   | ✓ Passed  | 10 s
multiwallet.py                 | ✓ Passed  | 16 s
net.py                         | ✓ Passed  | 9 s
nulldummy.py                   | ✓ Passed  | 12 s
p2p-compactblocks.py           | ✓ Passed  | 125 s
p2p-fullblocktest.py           | ✖ Failed  | 573 s
p2p-leaktests.py               | ✓ Passed  | 10 s
p2p-mempool.py                 | ✓ Passed  | 6 s
p2p-segwit.py                  | ✓ Passed  | 108 s
p2p-versionbits-warning.py     | ✓ Passed  | 19 s
preciousblock.py               | ✓ Passed  | 17 s
prioritise_transaction.py      | ✓ Passed  | 37 s
proxy_test.py                  | ✓ Passed  | 16 s
rawtransactions.py             | ✓ Passed  | 46 s
receivedby.py                  | ✓ Passed  | 40 s
reindex.py                     | ✓ Passed  | 22 s
resendwallettransactions.py    | ✓ Passed  | 7 s
rest.py                        | ✓ Passed  | 28 s
rpcnamedargs.py                | ✓ Passed  | 5 s
segwit.py                      | ✓ Passed  | 109 s
sendheaders.py                 | ✓ Passed  | 38 s
signmessages.py                | ✓ Passed  | 7 s
signrawtransactions.py         | ✓ Passed  | 5 s
test_script_address2.py        | ✓ Passed  | 20 s
txn_clone.py                   | ✓ Passed  | 26 s
txn_doublespend.py --mineblock | ✓ Passed  | 27 s
uptime.py                      | ✓ Passed  | 5 s
wallet-accounts.py             | ✓ Passed  | 55 s
wallet-dump.py                 | ✓ Passed  | 16 s
wallet-encryption.py           | ✓ Passed  | 14 s
wallet-hd.py                   | ✓ Passed  | 443 s
wallet.py                      | ✓ Passed  | 159 s
walletbackup.py                | ✖ Failed  | 248 s
zapwallettxes.py               | ✓ Passed  | 22 s
zmq_test.py                    | ✓ Passed  | 12 s

ALL                            | ✖ Failed  | 3083 s (accumulated) 
```
The failures appear due to timeout when shutting down a riffcashd daemon:
```
walletbackup.py failed, Duration: 248 s

stdout:
2018-02-25 13:44:13.347000 TestFramework (INFO): Initializing test directory /tmp/riffcash_test_runner_20180225_084321/walletbackup_211
2018-02-25 13:44:24.365000 TestFramework (INFO): Generating initial blockchain
2018-02-25 13:44:25.077000 TestFramework (INFO): Creating transactions
2018-02-25 13:45:13.099000 TestFramework (INFO): Backing up
2018-02-25 13:45:13.921000 TestFramework (INFO): More transactions
2018-02-25 13:46:11.862000 TestFramework (INFO): Restoring using wallet.dat
2018-02-25 13:46:22.029000 TestFramework (INFO): Re-starting nodes
2018-02-25 13:46:32.040000 TestFramework (INFO): Restoring using dumped wallet
2018-02-25 13:47:21.900000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 169, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/test_framework.py", line 152, in main
    self.run_test()
  File "[stripped]/riffcash/riffcash-core/test/functional/walletbackup.py", line 185, in run_test
    self.nodes[0].importwallet(tmpdir + "/node0/wallet.dump")
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 126, in _request
    return self._get_response()
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 176, in _get_response
    self.__conn.timeout)})
test_framework.authproxy.JSONRPCException: 'importwallet' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
2018-02-25 13:47:21.902000 TestFramework (INFO): Stopping nodes
2018-02-25 13:47:21.902000 TestFramework (ERROR): Unable to stop node
Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/test_framework.py", line 261, in stop_node
    self.nodes[i].stop()
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 125, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 974, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```
The timeout problem will be addressed in another issue. Closing this one.
