### ISSUE TITLE
walletbackup.py unit test fails with socket timeout exception

### ISSUE THREAD

**Issue by brat000012001** [brat000012001/riffcash-core#4]
There are a few unit tests in the python test suite that are failing with socket timeout exception. Need to investigate whether the issue is benign or there is a deeper problem with the blockchain daemon. The details of the exception are shown below:

```
walletbackup.py failed, Duration: 248 s

stdout:
2018-02-25 13:44:13.347000 TestFramework (INFO): Initializing test directory /tmp/riffcash_test_runner_20180225_084321/walletbackup_211
2018-02-25 13:44:24.365000 TestFramework (INFO): Generating initial blockchain
2018-02-25 13:44:25.077000 TestFramework (INFO): Creating transactions
2018-02-25 13:45:13.099000 TestFramework (INFO): Backing up
2018-02-25 13:45:13.921000 TestFramework (INFO): More transactions
2018-02-25 13:46:11.862000 TestFramework (INFO): Restoring using wallet.dat
2018-02-25 13:46:22.029000 TestFramework (INFO): Re-starting nodes
2018-02-25 13:46:32.040000 TestFramework (INFO): Restoring using dumped wallet
2018-02-25 13:47:21.900000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 169, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/test_framework.py", line 152, in main
    self.run_test()
  File "[stripped]/riffcash/riffcash-core/test/functional/walletbackup.py", line 185, in run_test
    self.nodes[0].importwallet(tmpdir + "/node0/wallet.dump")
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 126, in _request
    return self._get_response()
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 176, in _get_response
    self.__conn.timeout)})
test_framework.authproxy.JSONRPCException: 'importwallet' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
2018-02-25 13:47:21.902000 TestFramework (INFO): Stopping nodes
2018-02-25 13:47:21.902000 TestFramework (ERROR): Unable to stop node
Traceback (most recent call last):
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/test_framework.py", line 261, in stop_node
    self.nodes[i].stop()
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "[stripped]/riffcash/riffcash-core/test/functional/test_framework/authproxy.py", line 125, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 974, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```

**Comment by brat000012001** [comment]
The test passes when running it individually:
`
$ test/functional/test_runner.py walletbackup.py
`
The test produces the following output:
```
walletbackup.py passed, Duration: 183 s
TEST            | STATUS    | DURATION
walletbackup.py | ✓ Passed  | 183 s
ALL             | ✓ Passed  | 183 s (accumulated) 
Runtime: 183 s
```
