### ISSUE TITLE
p2p-fullblocktest.py integration test failed

### ISSUE THREAD

**Issue by brat000012001** [brat000012001/riffcash-core#5]
The integration test fails when running the integration test suite. The test produces the following error:
```
2p-fullblocktest.py failed, Duration: 585 s

stdout:
2018-07-01 03:24:00.336000 TestFramework (INFO): Initializing test directory /tmp/riffcash_test_runner_20180630_232302/p2p-fullblocktest_97
2018-07-01 03:24:04.109000 TestFramework.mininode (INFO): Connecting to Riffcash Node: 127.0.0.1:11776
2018-07-01 03:24:04.332000 TestFramework.comptool (INFO): Test 1: PASS
2018-07-01 03:24:05.023000 TestFramework.comptool (INFO): Test 2: PASS
2018-07-01 03:24:05.205000 TestFramework.comptool (INFO): Test 3: PASS
2018-07-01 03:24:05.438000 TestFramework.comptool (INFO): Test 4: PASS
2018-07-01 03:24:05.540000 TestFramework.comptool (INFO): Test 5: PASS
2018-07-01 03:24:05.723000 TestFramework.comptool (INFO): Test 6: PASS
2018-07-01 03:24:05.826000 TestFramework.comptool (INFO): Test 7: PASS
2018-07-01 03:24:06.047000 TestFramework.comptool (INFO): Test 8: PASS
2018-07-01 03:24:06.149000 TestFramework.comptool (INFO): Test 9: PASS
2018-07-01 03:24:06.251000 TestFramework.comptool (INFO): Test 10: PASS
2018-07-01 03:24:06.354000 TestFramework.comptool (INFO): Test 11: PASS
2018-07-01 03:24:06.457000 TestFramework.comptool (INFO): Test 12: PASS
2018-07-01 03:24:06.559000 TestFramework.comptool (INFO): Test 13: PASS
2018-07-01 03:24:06.664000 TestFramework.comptool (INFO): Test 14: PASS
2018-07-01 03:24:06.766000 TestFramework.comptool (INFO): Test 15: PASS
2018-07-01 03:24:06.849000 TestFramework.comptool (INFO): Test 16: PASS
2018-07-01 03:24:07.096000 TestFramework.comptool (INFO): Test 17: PASS
2018-07-01 03:24:07.160000 TestFramework.comptool (INFO): Test 18: PASS
2018-07-01 03:24:07.262000 TestFramework.comptool (INFO): Test 19: PASS
2018-07-01 03:24:07.364000 TestFramework.comptool (INFO): Test 20: PASS
2018-07-01 03:24:07.516000 TestFramework.comptool (INFO): Test 21: PASS
2018-07-01 03:24:07.618000 TestFramework.comptool (INFO): Test 22: PASS
2018-07-01 03:24:07.720000 TestFramework.comptool (INFO): Test 23: PASS
2018-07-01 03:24:07.826000 TestFramework.comptool (INFO): Test 24: PASS
2018-07-01 03:24:08.119000 TestFramework.comptool (INFO): Test 25: PASS
2018-07-01 03:24:08.287000 TestFramework.comptool (INFO): Test 26: PASS
2018-07-01 03:24:08.389000 TestFramework.comptool (INFO): Test 27: PASS
2018-07-01 03:24:08.491000 TestFramework.comptool (INFO): Test 28: PASS
2018-07-01 03:24:08.595000 TestFramework.comptool (INFO): Test 29: PASS
2018-07-01 03:24:08.749000 TestFramework.comptool (INFO): Test 30: PASS
2018-07-01 03:24:08.851000 TestFramework.comptool (INFO): Test 31: PASS
2018-07-01 03:24:09.035000 TestFramework.comptool (INFO): Test 32: PASS
2018-07-01 03:24:09.271000 TestFramework.comptool (INFO): Test 33: PASS
2018-07-01 03:24:09.324000 TestFramework.comptool (INFO): Test 34: PASS
2018-07-01 03:24:09.610000 TestFramework.comptool (INFO): Test 35: PASS
2018-07-01 03:24:09.713000 TestFramework.comptool (INFO): Test 36: PASS
2018-07-01 03:24:09.910000 TestFramework.comptool (INFO): Test 37: PASS
2018-07-01 03:24:10.024000 TestFramework.comptool (INFO): Test 38: PASS
2018-07-01 03:24:10.127000 TestFramework.comptool (INFO): Test 39: PASS
2018-07-01 03:24:10.229000 TestFramework.comptool (INFO): Test 40: PASS
2018-07-01 03:24:12.135000 TestFramework.comptool (INFO): Test 41: PASS
2018-07-01 03:24:15.886000 TestFramework.comptool (INFO): Test 42: PASS
2018-07-01 03:24:17.233000 TestFramework.comptool (INFO): Test 43: PASS
2018-07-01 03:24:17.335000 TestFramework.comptool (INFO): Test 44: PASS
2018-07-01 03:24:17.847000 TestFramework.comptool (INFO): Test 45: PASS
2018-07-01 03:24:18.429000 TestFramework.comptool (INFO): Test 46: PASS
2018-07-01 03:24:18.531000 TestFramework.comptool (INFO): Test 47: PASS
2018-07-01 03:24:18.633000 TestFramework.comptool (INFO): Test 48: PASS
2018-07-01 03:24:18.734000 TestFramework.comptool (INFO): Test 49: PASS
2018-07-01 03:24:18.836000 TestFramework.comptool (INFO): Test 50: PASS
2018-07-01 03:24:18.939000 TestFramework.comptool (INFO): Test 51: PASS
2018-07-01 03:24:19.045000 TestFramework.comptool (INFO): Test 52: PASS
2018-07-01 03:24:19.099000 TestFramework.comptool (INFO): Test 53: PASS
2018-07-01 03:24:19.202000 TestFramework.comptool (INFO): Test 54: PASS
2018-07-01 03:24:19.306000 TestFramework.comptool (INFO): Test 55: PASS
2018-07-01 03:24:19.411000 TestFramework.comptool (INFO): Test 56: PASS
2018-07-01 03:24:19.863000 TestFramework.comptool (INFO): Test 57: PASS
2018-07-01 03:24:19.968000 TestFramework.comptool (INFO): Test 58: PASS
2018-07-01 03:24:20.074000 TestFramework.comptool (INFO): Test 59: PASS
2018-07-01 03:24:20.557000 TestFramework.comptool (INFO): Test 60: PASS
2018-07-01 03:24:20.708000 TestFramework.comptool (INFO): Test 61: PASS
2018-07-01 03:24:20.813000 TestFramework.comptool (INFO): Test 62: PASS
2018-07-01 03:24:20.916000 TestFramework.comptool (INFO): Test 63: PASS
2018-07-01 03:24:21.419000 TestFramework.comptool (INFO): Test 64: PASS
2018-07-01 03:24:21.523000 TestFramework.comptool (INFO): Test 65: PASS
2018-07-01 03:24:21.627000 TestFramework.comptool (INFO): Test 66: PASS
2018-07-01 03:24:21.731000 TestFramework.comptool (INFO): Test 67: PASS
2018-07-01 03:24:22.008000 TestFramework.comptool (INFO): Test 68: PASS
2018-07-01 03:24:22.629000 TestFramework.comptool (INFO): Test 69: PASS
2018-07-01 03:24:23.278000 TestFramework.comptool (INFO): Test 70: PASS
2018-07-01 03:24:23.383000 TestFramework.comptool (INFO): Test 71: PASS
2018-07-01 03:24:23.488000 TestFramework.comptool (INFO): Test 72: PASS
2018-07-01 03:24:23.593000 TestFramework.comptool (INFO): Test 73: PASS
2018-07-01 03:24:24.148000 TestFramework.comptool (INFO): Test 74: PASS
2018-07-01 03:24:24.253000 TestFramework.comptool (INFO): Test 75: PASS
2018-07-01 03:24:24.358000 TestFramework.comptool (INFO): Test 76: PASS
2018-07-01 03:24:25.000000 TestFramework.comptool (INFO): Test 77: PASS
2018-07-01 03:24:25.120000 TestFramework.comptool (INFO): Test 78: PASS
2018-07-01 03:24:25.225000 TestFramework.comptool (INFO): Test 79: PASS
2018-07-01 03:24:25.781000 TestFramework.comptool (INFO): Test 80: PASS
2018-07-01 03:24:26.537000 TestFramework.comptool (INFO): Test 81: PASS
2018-07-01 03:24:27.767000 TestFramework.comptool (INFO): Test 82: PASS
2018-07-01 03:24:29.144000 TestFramework.comptool (INFO): Test 83: PASS
2018-07-01 03:24:30.352000 TestFramework.comptool (INFO): Test 84: PASS
2018-07-01 03:24:30.466000 TestFramework.comptool (INFO): Test 85: PASS
2018-07-01 03:24:30.580000 TestFramework.comptool (INFO): Test 86: PASS
2018-07-01 03:24:32.066000 TestFramework.comptool (INFO): Test 87: PASS
2018-07-01 03:24:33.264000 TestFramework.comptool (INFO): Test 88: PASS
2018-07-01 03:24:34.428000 TestFramework.comptool (INFO): Test 89: PASS
2018-07-01 03:24:34.585000 TestFramework.comptool (INFO): Test 90: PASS
2018-07-01 03:24:35.505000 TestFramework.comptool (INFO): Test 91: PASS
2018-07-01 03:24:35.662000 TestFramework.comptool (INFO): Test 92: PASS
2018-07-01 03:24:36.685000 TestFramework.comptool (INFO): Test 93: PASS
2018-07-01 03:24:36.794000 TestFramework.comptool (INFO): Test 94: PASS
2018-07-01 03:30:42.389000 TestFramework.comptool (INFO): Test 95: PASS
2018-07-01 03:31:28.201000 TestFramework.comptool (INFO): Test 96: PASS
2018-07-01 03:32:30.592000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "test/functional/test_framework/test_framework.py", line 152, in main
    self.run_test()
  File "test/functional/p2p-fullblocktest.py", line 73, in run_test
    self.test.run()
  File "test/functional/test_framework/comptool.py", line 356, in run
    raise AssertionError("Test failed at test %d" % test_number)
AssertionError: Test failed at test 97
2018-07-01 03:32:30.594000 TestFramework (INFO): Stopping nodes


stderr:
Traceback (most recent call last):
  File "test/functional/p2p-fullblocktest.py", line 1290, in <module>
    FullBlockTest().main()
  File "test/functional/test_framework/test_framework.py", line 175, in main
    self.stop_nodes()
  File "test/functional/test_framework/test_framework.py", line 272, in stop_nodes
    self.stop_node(i)
  File "test/functional/test_framework/test_framework.py", line 264, in stop_node
    return_code = self.bitcoind_processes[i].wait(timeout=BITCOIND_PROC_WAIT_TIMEOUT)
  File "/usr/lib/python3.5/subprocess.py", line 1650, in wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['src/riffcashd', '-datadir=/tmp/riffcash_test_runner_20180630_232302/p2p-fullblocktest_97/node0', '-server', '-keypool=1', '-discover=0', '-rest', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-mocktime=0', '-uacomment=testnode0', '-whitelist=127.0.0.1']' timed out after 60 seconds

```

**Comment by brat000012001** [comment]
Note that the test fails even when run individually
